### ISSUE TITLE
InvalidArgumentException thrown when enabling module d_product or editing view products_list

### ISSUE THREAD

**Issue by bmunslow** [droptica/droopler#121] opened 2019-02-18 08:17 UTC
On a clean droopler install, when you enable module `d_product`, the following error is thrown:

`InvalidArgumentException: $string ("1") must be a string. in  Drupal\Core\StringTranslation\TranslatableMarkup->__construct() (line 132)`

The same happens if you try to edit and save view `products_list`.

After doing some debugging, I've traced the error down to the following:

File `/modules/custom/d_product/config/install/views.view.products_list.yml`, line 69, contains invalid value for parameter `bef_slider_step`, namely:

`bef_slider_step: !!float 1`

Changing this value to `null` (as all other options in this block are) fixes the issue:

`bef_slider_step: null`

**Comment by damian-sikora-droptica** [comment] 2019-07-04 09:05
Hello @bmunslow,
could you please check again if this issue still persists? We have checked this on our side and we can't reproduce such issue.

**Comment by grzegorz-pietrzak-droptica** [comment] 2019-09-04 07:29
Hello @bmunslow, we are closing the ticket because we cannot reproduce the issue. If it still persists on your side, please provide your versions of BEF, Drupal Core, and PHP.

**Comment by bmunslow** [comment] 2019-09-17 19:35
Hi @grzegorz-pietrzak-droptica 

Thanks for looking into this.

I just checked again, clean Droopler install, and the issue persists:

```
InvalidArgumentException: $string ("1") must be a string. en Drupal\Core\StringTranslation\TranslatableMarkup->__construct() (linea 132 de/Sites/droopler.localhost/web/core/lib/Drupal/Core/StringTranslation/TranslatableMarkup.php).
```

Please note that, in order to reproduce it, you must choose any language other than English when installing Drupal:

![image](https://user-images.githubusercontent.com/295192/65049826-b8184280-d966-11e9-8ddb-24d2c9992221.png)

This forces translation fetching for newly installed modules and hits the fatal error described in this issue when enabling module `d_product` or editing the view `products_list`

Other relevant information about my setup and Drupal install:

**PHP** 7.2.10
**BEF** 8.x-3.0-alpha6
**Drupal Core** 8.7.7

Profile installed following suggested method in [Droopler Skeleton repository](https://github.com/droptica/droopler_project):

```
$ composer create-project droptica/droopler-project droopler
$ cd droopler
$ composer drupal-scaffold
$ composer install
```

**Comment by grzegorz-pietrzak-droptica** [comment] 2020-01-21 06:11
This was already fixed in latest develop branch, @bmunslow thanks for pointing this out :-)

**Closed by grzegorz-pietrzak-droptica** 2020-01-21 06:11 UTC
